In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import yaml as ym 
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer

In [4]:
with open("../config.yaml","r",encoding="utf-8") as file:
    config=ym.safe_load(file)

In [ ]:
df1=pd.read_csv(config['paths']['raw_data'][0])
df1.head()

,RefSeq_accession_number,gene_symbol,gene_name,AO-A12D.01TCGA,C8-A131.01TCGA,AO-A12B.01TCGA,BH-A18Q.02TCGA,C8-A130.02TCGA,C8-A138.03TCGA,E2-A154.03TCGA,...,AO-A12B.34TCGA,A2-A0SW.35TCGA,AO-A0JL.35TCGA,BH-A0BV.35TCGA,A2-A0YM.36TCGA,BH-A0C7.36TCGA,A2-A0SX.36TCGA,263d3f-I.CPTAC,blcdb9-I.CPTAC,c4155b-C.CPTAC
0,NP_958782,PLEC,plectin isoform 1,1.096131,2.609943,-0.659828,0.195341,-0.494060,2.765081,0.862659,...,-0.963904,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.398560,0.598585,-0.191285,0.566975
1,NP_958785,NaN,plectin isoform 1g,1.111370,2.650422,-0.648742,0.215413,-0.503899,2.779709,0.870186,...,-0.938210,-0.487772,-0.10668,-0.055893,0.658143,-0.547749,-0.392601,0.606697,-0.183918,0.578702
2,NP_958786,PLEC,plectin isoform 1a,1.111370,2.650422,-0.654285,0.215413,-0.500619,2.779709,0.870186,...,-0.943919,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
3,NP_000436,NaN,plectin isoform 1c,1.107561,2.646374,-0.632113,0.205377,-0.510459,2.797995,0.866423,...,-0.935355,-0.487772,-0.10668,-0.055893,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
4,NP_958781,NaN,plectin isoform 1e,1.115180,2.646374,-0.640428,0.215413,-0.503899,2.787023,0.870186,...,-0.935355,-0.503853,-0.10668,-0.062523,0.651264,-0.556675,-0.395581,0.603993,-0.167079,0.576747

In [5]:
df1.transpose().head()

,0,1,2,3,4,5,6,7,8,9,...,12543,12544,12545,12546,12547,12548,12549,12550,12551,12552
RefSeq_accession_number,NP_958782,NP_958785,NP_958786,NP_000436,NP_958781,NP_958780,NP_958783,NP_958784,NP_112598,NP_001611,...,NP_001193600,NP_061134,NP_932347,NP_003593,NP_997203,NP_001191293,NP_775791,NP_004065,NP_068752,NP_219494
gene_symbol,PLEC,NaN,PLEC,NaN,NaN,PLEC,PLEC,NaN,NaN,AHNAK,...,NaN,BATF3,SCML4,FKBP6,OTUD6A,NaN,NaN,COX8A,MIIP,KIAA1737
gene_name,plectin isoform 1,plectin isoform 1g,plectin isoform 1a,plectin isoform 1c,plectin isoform 1e,plectin isoform 1f,plectin isoform 1d,plectin isoform 1b,epiplakin,neuroblast differentiation-associated protein ...,...,protein RIC-3 isoform c precursor,basic leucine zipper transcriptional factor AT...,sex comb on midleg-like protein 4,peptidyl-prolyl cis-trans isomerase FKBP6 isof...,OTU domain-containing protein 6A,protein FAM24B precursor,putative uncharacterized protein C9orf62,"cytochrome c oxidase subunit 8A, mitochondrial",migration and invasion-inhibitory protein,uncharacterized protein KIAA1737
AO-A12D.01TCGA,1.096131,1.11137,1.11137,1.107561,1.11518,1.107561,1.11137,1.11137,-1.51739,0.482754,...,NaN,NaN,NaN,-0.340163,NaN,NaN,NaN,NaN,-0.633517,12.666488
C8-A131.01TCGA,2.609943,2.650422,2.650422,2.646374,2.646374,2.646374,2.650422,2.650422,3.909313,-1.045294,...,NaN,NaN,NaN,3.451902,NaN,NaN,NaN,NaN,4.840325,0.140736